// Pricing is approximate — pulled from public market reports (Redfin,
// Zillow, Miami Today, local brokerage market reports) as of mid-2026, and
// moves constantly. Treat every figure here as a starting reference point,
// not a valuation — always confirm with current MLS comps.
const neighborhoods = [
  {
    slug: "brickell",
    name: "Brickell",
    image: "/images/brickell.jpg",
    tagline: {
      en: "High-rise, walkable, young professionals",
      es: "Rascacielos, transitable a pie, jóvenes profesionales",
      fr: "Gratte-ciels, quartier piétonnier, jeunes professionnels",
      ht: "Gratsyèl, katye pou mache, jèn pwofesyonèl",
      pt: "Arranha-céus, fácil de caminhar, jovens profissionais",
      it: "Grattacieli, quartiere pedonale, giovani professionisti",
    },
    history: {
      en: "Once known as \"Millionaire's Row\" for the mansions lining Brickell Avenue in the early 1900s, Brickell reinvented itself as Miami's financial district — the \"Wall Street of the South\" — starting in the 1970s. Since the 2000s it's exploded into one of the densest, most vertical residential neighborhoods in the country.",
      es: "Antes conocida como la \"Milla de los Millonarios\" por las mansiones a lo largo de Brickell Avenue a principios del siglo XX, Brickell se reinventó como el distrito financiero de Miami — el \"Wall Street del Sur\" — a partir de la década de 1970. Desde la década de 2000 se ha convertido en uno de los vecindarios residenciales más densos y verticales del país.",
      fr: "Autrefois surnommée « Millionaire's Row » pour les manoirs qui bordaient Brickell Avenue au début des années 1900, Brickell s'est réinventée en district financier de Miami — le « Wall Street du Sud » — à partir des années 1970. Depuis les années 2000, elle est devenue l'un des quartiers résidentiels les plus denses et les plus verticaux du pays.",
      ht: "Yon fwa yo te rele li \"Millionaire's Row\" pou gwo kay rich ki te alinye sou Brickell Avenue nan kòmansman ane 1900 yo, Brickell te reenvante tèt li kòm distri finansye Miami — \"Wall Street Sid la\" — kòmanse nan ane 1970 yo. Depi ane 2000 yo li eksploze pou li vin youn nan katye rezidansyèl ki pi dans, ki pi vètikal nan peyi a.",
      pt: "Antes conhecida como \"Millionaire's Row\" pelas mansões que margeavam a Brickell Avenue no início dos anos 1900, Brickell se reinventou como o distrito financeiro de Miami — a \"Wall Street do Sul\" — a partir da década de 1970. Desde os anos 2000, explodiu e se tornou um dos bairros residenciais mais densos e verticais do país.",
      it: "Un tempo conosciuta come \"Millionaire's Row\" per le ville che costeggiavano Brickell Avenue all'inizio del XX secolo, Brickell si è reinventata come distretto finanziario di Miami — la \"Wall Street del Sud\" — a partire dagli anni '70. Dagli anni 2000 è esplosa diventando uno dei quartieri residenziali più densi e verticali del paese.",
    },
    pricing: {
      singleFamily: { value: null, note: { en: "Almost no single-family stock — Brickell is nearly all high-rise.", es: "Casi no hay viviendas unifamiliares — Brickell es casi todo rascacielos." } },
      condo: { value: 790000, note: { en: "Entry-level 1BR units run roughly $300K–$500K.", es: "Las unidades de 1 habitación de nivel inicial rondan los $300,000–$500,000." } },
    },
  },
  {
    slug: "coral-gables",
    name: "Coral Gables",
    image: "/images/coral-gables.jpg",
    tagline: {
      en: "Tree-lined, historic, family-oriented",
      es: "Arbolado, histórico, orientado a familias",
      fr: "Arboré, historique, familial",
      ht: "Plen pyebwa, istorik, oryante pou fanmi",
      pt: "Arborizado, histórico, voltado para famílias",
      it: "Alberato, storico, a misura di famiglia",
    },
    history: {
      en: "Built by George Merrick starting in 1921, Coral Gables was one of America's first master-planned communities — a \"City Beautiful\" of Mediterranean Revival architecture, grand boulevards, and coral-rock landmarks like the Biltmore Hotel and Venetian Pool. It remains one of Miami-Dade's most tightly regulated, historic neighborhoods.",
      es: "Construida por George Merrick a partir de 1921, Coral Gables fue una de las primeras comunidades planificadas de Estados Unidos — una \"Ciudad Bella\" de arquitectura de Estilo Mediterráneo Revival, grandes bulevares y monumentos de piedra coralina como el Hotel Biltmore y la Piscina Veneciana. Sigue siendo uno de los vecindarios históricos más regulados de Miami-Dade.",
      fr: "Construite par George Merrick à partir de 1921, Coral Gables fut l'une des premières communautés planifiées d'Amérique — une « Cité Idéale » d'architecture néo-méditerranéenne, de grands boulevards et de monuments en pierre de corail comme le Biltmore Hotel et le Venetian Pool. Elle reste l'un des quartiers historiques les plus strictement réglementés de Miami-Dade.",
      ht: "Konstwi pa George Merrick kòmanse an 1921, Coral Gables te youn nan premye kominote Amerik ki te planifye antyeman — yon \"Vil Bèl\" ak achitekti Mediterane Revival, gwo boulva, ak monimen wòch koray tankou Biltmore Hotel ak Venetian Pool. Li rete youn nan katye istorik Miami-Dade ki pi byen reglemante.",
      pt: "Construída por George Merrick a partir de 1921, Coral Gables foi uma das primeiras comunidades planejadas da América — uma \"Cidade Bela\" de arquitetura de estilo mediterrâneo, grandes avenidas e marcos em pedra de coral como o Biltmore Hotel e a Venetian Pool. Continua sendo um dos bairros históricos mais rigidamente regulamentados de Miami-Dade.",
      it: "Costruita da George Merrick a partire dal 1921, Coral Gables fu una delle prime comunità pianificate d'America — una \"Città Ideale\" di architettura in stile mediterraneo, grandi viali e monumenti in roccia corallina come l'Hotel Biltmore e la Venetian Pool. Resta uno dei quartieri storici più rigidamente regolamentati di Miami-Dade.",
    },
    pricing: {
      singleFamily: { value: 2400000, note: { en: "Among the highest in Miami-Dade, driven by historic estates and strict zoning.", es: "Entre los más altos de Miami-Dade, impulsado por propiedades históricas y zonificación estricta." } },
      condo: { value: 650000, note: { en: "Fewer condo towers than Brickell — most stock is mid-rise.", es: "Menos torres de condominios que Brickell — la mayoría son edificios de baja altura." } },
    },
  },
  {
    slug: "wynwood",
    name: "Wynwood",
    image: "/images/wynwood.jpg",
    tagline: {
      en: "Art, lofts, nightlife",
      es: "Arte, lofts, vida nocturna",
      fr: "Art, lofts, vie nocturne",
      ht: "Atizay, lof, lavi nannwit",
      pt: "Arte, lofts, vida noturna",
      it: "Arte, loft, vita notturna",
    },
    history: {
      en: "A former garment-district and warehouse area, Wynwood was transformed starting in 2009 when developer Tony Goldman commissioned the Wynwood Walls mural project. It's now Miami's arts and nightlife district, with warehouse conversions, breweries, and a fast-growing wave of new-construction lofts and mixed-use towers.",
      es: "Antiguo distrito de confección y bodegas, Wynwood se transformó a partir de 2009 cuando el desarrollador Tony Goldman encargó el proyecto de murales Wynwood Walls. Ahora es el distrito de arte y vida nocturna de Miami, con bodegas convertidas, cervecerías y una ola creciente de lofts de nueva construcción y torres de uso mixto.",
      fr: "Ancien quartier de la confection et des entrepôts, Wynwood s'est transformé à partir de 2009 lorsque le promoteur Tony Goldman a commandé le projet de fresques murales Wynwood Walls. C'est aujourd'hui le quartier des arts et de la vie nocturne de Miami, avec des entrepôts reconvertis, des brasseries, et une vague croissante de lofts neufs et de tours à usage mixte.",
      ht: "Yon ansyen zòn distri rad ak depo, Wynwood te transfòme kòmanse an 2009 lè devlopè Tony Goldman te kòmande pwojè miral Wynwood Walls la. Kounye a se distri atizay ak lavi nannwit Miami, ak depo ki konvèti, brasri, ak yon vag k ap grandi vit nan lof nouvo konstriksyon ak tou itilizasyon mikste.",
      pt: "Antiga região de fábricas de roupas e galpões, Wynwood foi transformada a partir de 2009, quando o incorporador Tony Goldman encomendou o projeto de murais Wynwood Walls. Hoje é o distrito de arte e vida noturna de Miami, com galpões convertidos, cervejarias artesanais e uma onda crescente de lofts de construção nova e torres de uso misto.",
      it: "Ex quartiere dell'abbigliamento e dei magazzini, Wynwood si è trasformato a partire dal 2009, quando lo sviluppatore Tony Goldman commissionò il progetto di murales Wynwood Walls. Oggi è il quartiere dell'arte e della vita notturna di Miami, con magazzini riconvertiti, birrifici e un'ondata crescente di loft di nuova costruzione e torri a uso misto.",
    },
    pricing: {
      singleFamily: { value: null, note: { en: "Very limited single-family inventory — the area is dominated by lofts and new towers.", es: "Inventario unifamiliar muy limitado — el área está dominada por lofts y torres nuevas." } },
      condo: { value: 550000, note: { en: "Loft and condo prices vary widely by building age and finish level.", es: "Los precios de lofts y condominios varían mucho según la antigüedad del edificio y el nivel de acabado." } },
    },
  },
  {
    slug: "coconut-grove",
    name: "Coconut Grove",
    image: "/images/coconut-grove.jpg",
    tagline: {
      en: "Bayfront, laid-back, established",
      es: "Frente a la bahía, relajado, establecido",
      fr: "Front de baie, décontracté, établi",
      ht: "Bò benen, dekontrakte, byen etabli",
      pt: "Litoral da baía, descontraído, tradicional",
      it: "Sul mare, rilassato, consolidato",
    },
    history: {
      en: "Miami's oldest continuously inhabited neighborhood, Coconut Grove was settled in the 1800s by New England sailors and Bahamian immigrants, whose descendants still anchor the historic West Grove community. It grew into a bohemian, artsy enclave by the mid-1900s and remains one of Miami's leafiest, most laid-back areas.",
      es: "El vecindario habitado continuamente más antiguo de Miami, Coconut Grove fue colonizado en el siglo XIX por marineros de Nueva Inglaterra e inmigrantes bahameños, cuyos descendientes todavía anclan la comunidad histórica de West Grove. Se convirtió en un enclave bohemio y artístico a mediados del siglo XX y sigue siendo una de las áreas más arboladas y relajadas de Miami.",
      fr: "Quartier habité en continu le plus ancien de Miami, Coconut Grove fut colonisé au XIXe siècle par des marins de Nouvelle-Angleterre et des immigrants bahaméens, dont les descendants ancrent encore la communauté historique de West Grove. Il est devenu une enclave bohème et artistique au milieu du XXe siècle et reste l'une des zones les plus verdoyantes et décontractées de Miami.",
      ht: "Katye ki pi ansyen ki abite san rete nan Miami, Coconut Grove te etabli nan ane 1800 yo pa maren New England ak imigran Bahamyen, epi desandan yo toujou ankre kominote istorik West Grove la. Li te vin yon enklav boèm, atistik nan mitan ane 1900 yo epi li rete youn nan zòn ki gen plis pyebwa e ki pi dekontrakte nan Miami.",
      pt: "O bairro habitado continuamente mais antigo de Miami, Coconut Grove foi colonizado no século XIX por marinheiros da Nova Inglaterra e imigrantes bahamenses, cujos descendentes ainda são a base da histórica comunidade de West Grove. Tornou-se um enclave boêmio e artístico em meados do século XX e continua sendo uma das áreas mais arborizadas e descontraídas de Miami.",
      it: "Il quartiere abitato ininterrottamente più antico di Miami, Coconut Grove fu colonizzato nell'Ottocento da marinai del New England e immigrati bahamensi, i cui discendenti sono ancora il fulcro della storica comunità di West Grove. Divenne un'enclave bohémien e artistica verso la metà del Novecento e resta una delle zone più verdi e rilassate di Miami.",
    },
    pricing: {
      singleFamily: { value: 2700000, note: { en: "Among the priciest in the county, especially near the bay.", es: "Entre los más caros del condado, especialmente cerca de la bahía." } },
      condo: { value: 700000, note: { en: "Concentrated in a handful of bayfront and village-center buildings.", es: "Concentrado en un puñado de edificios frente a la bahía y en el centro del pueblo." } },
    },
  },
  {
    slug: "doral",
    name: "Doral",
    image: "/images/doral.jpg",
    tagline: {
      en: "New construction, family suburbs",
      es: "Construcción nueva, suburbios familiares",
      fr: "Constructions neuves, banlieues familiales",
      ht: "Nouvo konstriksyon, sibèb fanmi",
      pt: "Construções novas, subúrbios familiares",
      it: "Nuove costruzioni, sobborghi familiari",
    },
    history: {
      en: "Named for founders Doris and Alfred Kaskel (\"Dor-Al\"), Doral was developed in the 1960s around a golf resort and incorporated as its own city in 2003. Its proximity to Miami International Airport and business parks fueled explosive growth as a hub for Venezuelan and other Latin American expat communities.",
      es: "Nombrado en honor a sus fundadores Doris y Alfred Kaskel (\"Dor-Al\"), Doral se desarrolló en la década de 1960 alrededor de un resort de golf y se incorporó como ciudad propia en 2003. Su cercanía al Aeropuerto Internacional de Miami y a parques empresariales impulsó un crecimiento explosivo como centro para comunidades de expatriados venezolanos y otros latinoamericanos.",
      fr: "Nommée d'après ses fondateurs Doris et Alfred Kaskel (« Dor-Al »), Doral fut développée dans les années 1960 autour d'un complexe de golf et devint une ville à part entière en 2003. Sa proximité avec l'aéroport international de Miami et les parcs d'affaires a alimenté une croissance explosive en tant que pôle pour les communautés d'expatriés vénézuéliens et autres Latino-Américains.",
      ht: "Yo te nonmen li dapre fondatè Doris ak Alfred Kaskel (\"Dor-Al\"), Doral te devlope nan ane 1960 yo alantou yon rezò gòlf epi li te vin yon vil pou kont li an 2003. Pwoksimite li ak Ayewopò Entènasyonal Miami ak pak biznis yo te alimante yon kwasans eksplozif kòm yon sant pou kominote ekspatriye Venezyelyen ak lòt Amerikendlatin.",
      pt: "Batizada em homenagem aos fundadores Doris e Alfred Kaskel (\"Dor-Al\"), Doral foi desenvolvida na década de 1960 ao redor de um resort de golfe e se tornou uma cidade própria em 2003. Sua proximidade com o Aeroporto Internacional de Miami e parques empresariais impulsionou um crescimento explosivo como polo para comunidades de expatriados venezuelanos e outros latino-americanos.",
      it: "Chiamata così in onore dei fondatori Doris e Alfred Kaskel (\"Dor-Al\"), Doral fu sviluppata negli anni '60 attorno a un resort golfistico e divenne una città a sé stante nel 2003. La vicinanza all'Aeroporto Internazionale di Miami e ai parchi commerciali ne alimentò una crescita esplosiva come polo per le comunità di espatriati venezuelani e di altri latinoamericani.",
    },
    pricing: {
      singleFamily: { value: 1000000, note: { en: "Mostly newer-construction homes in gated communities.", es: "Principalmente casas de construcción reciente en comunidades cerradas." } },
      condo: { value: 476000, note: { en: "Large, relatively young condo inventory compared to the rest of the county.", es: "Inventario de condominios grande y relativamente joven comparado con el resto del condado." } },
    },
  },
  {
    slug: "midtown-edgewater",
    name: "Midtown / Edgewater",
    image: "/images/midtown-edgewater.jpg",
    tagline: {
      en: "Trendy, waterfront high-rises, walkable",
      es: "De moda, rascacielos junto al agua, transitable a pie",
      fr: "Branché, gratte-ciels en bord de mer, quartier piétonnier",
      ht: "Nan mòd, gratsyèl bò dlo, katye pou mache",
      pt: "Moderno, prédios altos à beira-mar, fácil de caminhar",
      it: "Alla moda, grattacieli sul mare, quartiere pedonale",
    },
    history: {
      en: "Midtown was built in the 2000s on a former FEC railway yard as a master-planned, walkable district of shops and condos, while neighboring Edgewater — an older Biscayne Bay-front area — has filled in rapidly with new high-rise towers, becoming one of Miami's fastest-growing condo corridors.",
      es: "Midtown se construyó en la década de 2000 sobre un antiguo patio ferroviario de FEC como un distrito planificado y transitable a pie de tiendas y condominios, mientras que la vecina Edgewater — un área más antigua frente a la Bahía de Biscayne — se ha llenado rápidamente de nuevas torres de gran altura, convirtiéndose en uno de los corredores de condominios de más rápido crecimiento de Miami.",
      fr: "Midtown fut construit dans les années 2000 sur un ancien dépôt ferroviaire de la FEC comme un district planifié et piétonnier de boutiques et de condos, tandis que la voisine Edgewater — une zone plus ancienne en front de la baie de Biscayne — s'est rapidement remplie de nouvelles tours de grande hauteur, devenant l'un des corridors de condos à la croissance la plus rapide de Miami.",
      ht: "Yo te konstwi Midtown nan ane 2000 yo sou yon ansyen depo tren FEC kòm yon distri byen planifye, ki bon pou mache ak magazen ak kondo, pandan Edgewater vwazen an — yon zòn pi ansyen bò Bwa Biscayne — te ranpli rapid ak nouvo gratsyèl, epi li vin youn nan koridò kondo k ap grandi pi vit nan Miami.",
      pt: "Midtown foi construída nos anos 2000 sobre um antigo pátio ferroviário da FEC como um distrito planejado e fácil de caminhar, com lojas e condomínios, enquanto a vizinha Edgewater — uma área mais antiga à beira da Baía de Biscayne — se preencheu rapidamente com novas torres altas, tornando-se um dos corredores de condomínios que mais crescem em Miami.",
      it: "Midtown fu costruita negli anni 2000 su un ex scalo ferroviario della FEC come distretto pianificato e pedonale di negozi e condomini, mentre la vicina Edgewater — un'area più vecchia affacciata sulla Baia di Biscayne — si è rapidamente riempita di nuove torri, diventando uno dei corridoi di condomini in più rapida crescita di Miami.",
    },
    pricing: {
      singleFamily: { value: null, note: { en: "Almost no single-family stock — this is a dense, high-rise corridor.", es: "Casi no hay propiedades unifamiliares — este es un corredor denso de gran altura." } },
      condo: { value: 715000, note: { en: "Newer waterfront towers in Edgewater command a premium over Midtown's older stock.", es: "Las torres más nuevas frente al agua en Edgewater tienen un precio superior al inventario más antiguo de Midtown." } },
    },
  },
  {
    slug: "miami-beach",
    name: "Miami Beach",
    image: "/images/miami-beach.jpg",
    tagline: {
      en: "Beaches, Art Deco, nightlife",
      es: "Playas, Art Deco, vida nocturna",
      fr: "Plages, Art déco, vie nocturne",
      ht: "Plaj, Art Deco, lavi nannwit",
      pt: "Praias, Art Déco, vida noturna",
      it: "Spiagge, Art Déco, vita notturna",
    },
    history: {
      en: "Built on reclaimed mangrove swamp starting in the 1910s by developer Carl Fisher, Miami Beach boomed with Art Deco hotels in the 1930s–40s, fell into decline mid-century, then was reborn as a fashion and nightlife capital during South Beach's 1980s–90s revival. Its Art Deco Historic District remains one of the largest in the US.",
      es: "Construida sobre un manglar recuperado a partir de la década de 1910 por el promotor Carl Fisher, Miami Beach floreció con hoteles Art Deco en los años 1930-40, decayó a mediados de siglo y luego renació como capital de la moda y la vida nocturna durante el renacimiento de South Beach en los años 1980-90. Su Distrito Histórico Art Deco sigue siendo uno de los más grandes de EE. UU.",
      fr: "Construite sur un marécage de mangrove asséché à partir des années 1910 par le promoteur Carl Fisher, Miami Beach a connu un essor avec ses hôtels Art déco dans les années 1930-40, puis a décliné au milieu du siècle avant de renaître comme capitale de la mode et de la vie nocturne lors de la renaissance de South Beach dans les années 1980-90. Son quartier historique Art déco reste l'un des plus grands des États-Unis.",
      ht: "Konstwi sou yon marekaj mangwov ki te ranbleye kòmanse nan ane 1910 yo pa devlopè Carl Fisher, Miami Beach te boom ak otèl Art Deco nan ane 1930-40 yo, li te tonbe an deklen nan mitan syèk la, epi apre li te renèt kòm kapital mòd ak lavi nannwit pandan renesans South Beach nan ane 1980-90 yo. Distri Istorik Art Deco li a rete youn nan pi gwo yo Ozetazini.",
      pt: "Construída sobre um mangue aterrado a partir da década de 1910 pelo incorporador Carl Fisher, Miami Beach prosperou com hotéis Art Déco nos anos 1930-40, entrou em declínio em meados do século, e depois renasceu como capital da moda e da vida noturna durante o renascimento de South Beach nos anos 1980-90. Seu Distrito Histórico Art Déco continua sendo um dos maiores dos EUA.",
      it: "Costruita su una palude di mangrovie bonificata a partire dagli anni '10 dallo sviluppatore Carl Fisher, Miami Beach visse un boom di hotel Art Déco negli anni '30-'40, per poi declinare a metà secolo e rinascere come capitale della moda e della vita notturna durante la rinascita di South Beach negli anni '80-'90. Il suo quartiere storico Art Déco resta uno dei più grandi degli Stati Uniti.",
    },
    pricing: {
      singleFamily: { value: 630000, note: { en: "Wide range — from small bungalows to waterfront mansions on the barrier island.", es: "Amplio rango — desde pequeños bungalós hasta mansiones frente al mar en la isla barrera." } },
      condo: { value: 539000, note: { en: "Includes everything from vintage Art Deco walk-ups to new luxury towers.", es: "Incluye desde edificios Art Deco vintage sin ascensor hasta nuevas torres de lujo." } },
    },
  },
  {
    slug: "downtown",
    name: "Downtown Miami",
    image: "/images/downtown.jpg",
    tagline: {
      en: "Urban core, business, transit hub",
      es: "Núcleo urbano, negocios, centro de transporte",
      fr: "Cœur urbain, affaires, pôle de transport",
      ht: "Sant iben, biznis, pwen tranzit",
      pt: "Centro urbano, negócios, polo de transporte",
      it: "Centro urbano, affari, snodo dei trasporti",
    },
    history: {
      en: "The site of Miami's original 1896 incorporation around the Miami River and Flagler Street, Downtown spent decades as a daytime-only business district before a 2000s condo boom filled it with residential towers, turning it into a genuine 24-hour urban core connected by Metromover and Metrorail.",
      es: "El sitio de la incorporación original de Miami en 1896 alrededor del río Miami y Flagler Street, el Downtown pasó décadas como distrito de negocios solo diurno antes de que un auge de condominios en la década de 2000 lo llenara de torres residenciales, convirtiéndolo en un verdadero núcleo urbano de 24 horas conectado por Metromover y Metrorail.",
      fr: "Site de l'incorporation originelle de Miami en 1896 autour de la rivière Miami et de Flagler Street, le Downtown a passé des décennies comme district d'affaires uniquement diurne avant qu'un boom des condos dans les années 2000 ne le remplisse de tours résidentielles, en faisant un véritable cœur urbain actif 24h/24, connecté par le Metromover et le Metrorail.",
      ht: "Sit orijinal enkòporasyon Miami nan 1896 alantou Rivyè Miami ak Flagler Street, Downtown te pase plizyè dekad kòm yon distri biznis ki fonksyone sèlman lajounen anvan yon boom kondo nan ane 2000 yo te ranpli l ak gratsyèl rezidansyèl, sa ki te fè l vin yon vrè sant iben 24 sou 24, konekte pa Metromover ak Metrorail.",
      pt: "Local da incorporação original de Miami em 1896, ao redor do Rio Miami e da Flagler Street, o Downtown passou décadas como um distrito comercial apenas diurno antes que um boom de condomínios nos anos 2000 o preenchesse com torres residenciais, transformando-o em um verdadeiro centro urbano 24 horas conectado pelo Metromover e Metrorail.",
      it: "Sede dell'incorporazione originale di Miami nel 1896 attorno al fiume Miami e a Flagler Street, il Downtown ha trascorso decenni come distretto commerciale solo diurno prima che un boom immobiliare di condomini negli anni 2000 lo riempisse di torri residenziali, trasformandolo in un vero centro urbano attivo 24 ore su 24, collegato da Metromover e Metrorail.",
    },
    pricing: {
      singleFamily: { value: null, note: { en: "No meaningful single-family market — Downtown is entirely high-rise.", es: "No hay un mercado unifamiliar significativo — el Downtown es completamente de rascacielos." } },
      condo: { value: 650000, note: { en: "Ranges from older 2000s-boom towers to brand-new luxury developments.", es: "Va desde torres más antiguas del auge de los 2000 hasta desarrollos de lujo completamente nuevos." } },
    },
  },
  {
    slug: "hialeah",
    name: "Hialeah",
    image: "/images/hialeah.jpg",
    tagline: {
      en: "Cuban heritage, dense, working-class",
      es: "Herencia cubana, denso, clase trabajadora",
      fr: "Héritage cubain, dense, classe populaire",
      ht: "Eritaj kiben, dans, klas travayè",
      pt: "Herança cubana, denso, classe trabalhadora",
      it: "Eredità cubana, denso, classe operaia",
    },
    history: {
      en: "Founded in 1925 around an aviation field and the Hialeah Park horse-racing track, Hialeah became a major landing point for Cuban immigrants from the 1960s onward. It's now one of the most densely populated cities in Florida and has one of the highest concentrations of Cuban-Americans in the country.",
      es: "Fundada en 1925 alrededor de un campo de aviación y el hipódromo Hialeah Park, Hialeah se convirtió en un importante punto de llegada para inmigrantes cubanos a partir de la década de 1960. Ahora es una de las ciudades más densamente pobladas de Florida y tiene una de las concentraciones más altas de cubanoamericanos del país.",
      fr: "Fondée en 1925 autour d'un terrain d'aviation et de l'hippodrome de Hialeah Park, Hialeah est devenue un point d'arrivée majeur pour les immigrants cubains à partir des années 1960. C'est aujourd'hui l'une des villes les plus densément peuplées de Floride, avec l'une des plus fortes concentrations de Cubano-Américains du pays.",
      ht: "Fonde an 1925 alantou yon jaden avyasyon ak pis kous chwal Hialeah Park, Hialeah te vin yon gwo pwen ateri pou imigran kiben depi ane 1960 yo. Kounye a se youn nan vil ki gen plis popilasyon dans nan Florid e li gen youn nan konsantrasyon Kibano-Ameriken ki pi wo nan peyi a.",
      pt: "Fundada em 1925 ao redor de um campo de aviação e da pista de corrida de cavalos do Hialeah Park, Hialeah se tornou um importante ponto de chegada para imigrantes cubanos a partir da década de 1960. Hoje é uma das cidades mais densamente povoadas da Flórida e tem uma das maiores concentrações de cubano-americanos do país.",
      it: "Fondata nel 1925 attorno a un campo di aviazione e all'ippodromo di Hialeah Park, Hialeah divenne un importante punto di arrivo per gli immigrati cubani a partire dagli anni '60. Oggi è una delle città più densamente popolate della Florida e ha una delle concentrazioni più alte di cubano-americani del paese.",
    },
    pricing: {
      singleFamily: { value: 450000, note: { en: "One of the more affordable single-family markets in Miami-Dade.", es: "Uno de los mercados unifamiliares más asequibles de Miami-Dade." } },
      condo: { value: 350000, note: { en: "Mostly older, smaller buildings compared to coastal neighborhoods.", es: "Principalmente edificios más antiguos y pequeños comparados con los vecindarios costeros." } },
    },
  },
  {
    slug: "miami-gardens",
    name: "Miami Gardens",
    image: "/images/miami-gardens.jpg",
    tagline: {
      en: "Suburban, diverse, family-focused",
      es: "Suburbano, diverso, orientado a familias",
      fr: "Suburbain, diversifié, axé sur la famille",
      ht: "Sibèben, divès, oryante sou fanmi",
      pt: "Suburbano, diverso, focado na família",
      it: "Suburbano, variegato, orientato alla famiglia",
    },
    history: {
      en: "Incorporated in 2003 from the Carol City and Opa-locka North areas, Miami Gardens is one of Miami-Dade's newest cities and has the largest Black population of any city in Florida. It's home to Hard Rock Stadium, home field for the Miami Dolphins and host to Super Bowls and the Miami Grand Prix.",
      es: "Incorporada en 2003 a partir de las áreas de Carol City y Opa-locka Norte, Miami Gardens es una de las ciudades más nuevas de Miami-Dade y tiene la mayor población afroamericana de cualquier ciudad de Florida. Es sede del Hard Rock Stadium, campo local de los Miami Dolphins y anfitrión de Super Bowls y el Gran Premio de Miami.",
      fr: "Constituée en ville en 2003 à partir des quartiers de Carol City et d'Opa-locka Nord, Miami Gardens est l'une des villes les plus récentes de Miami-Dade et compte la plus grande population noire de toutes les villes de Floride. Elle abrite le Hard Rock Stadium, domicile des Miami Dolphins et hôte de Super Bowls et du Grand Prix de Miami.",
      ht: "Enkòpore an 2003 apati zòn Carol City ak Opa-locka Nò, Miami Gardens se youn nan vil ki pi nouvo nan Miami-Dade epi li gen popilasyon Nwa ki pi gwo pase nenpòt lòt vil nan Florid. Se la Hard Rock Stadium ye, teren lakay Miami Dolphins ki te akeyi Super Bowl ak Miami Grand Prix.",
      pt: "Incorporada em 2003 a partir das áreas de Carol City e Opa-locka Norte, Miami Gardens é uma das cidades mais novas de Miami-Dade e tem a maior população negra entre todas as cidades da Flórida. É a sede do Hard Rock Stadium, campo dos Miami Dolphins e anfitrião de Super Bowls e do Grande Prêmio de Miami.",
      it: "Costituita come città nel 2003 a partire dalle zone di Carol City e Opa-locka North, Miami Gardens è una delle città più recenti di Miami-Dade e ha la più grande popolazione nera di qualsiasi città della Florida. Ospita l'Hard Rock Stadium, campo di casa dei Miami Dolphins e sede di Super Bowl e del Gran Premio di Miami.",
    },
    pricing: {
      singleFamily: { value: 400000, note: { en: "One of the more affordable single-family markets in the county.", es: "Uno de los mercados unifamiliares más asequibles del condado." } },
      condo: { value: 300000, note: { en: "Smaller condo/townhome market than coastal areas.", es: "Mercado de condominios/casas adosadas más pequeño que en las áreas costeras." } },
    },
  },
  {
    slug: "sunny-isles-beach",
    name: "Sunny Isles Beach",
    image: "/images/sunny-isles-beach.jpg",
    tagline: {
      en: "Oceanfront towers, luxury condos",
      es: "Torres frente al mar, condominios de lujo",
      fr: "Tours en front de mer, condos de luxe",
      ht: "Tou bò lanmè, kondo liks",
      pt: "Torres à beira-mar, condomínios de luxo",
      it: "Torri sul mare, condomini di lusso",
    },
    history: {
      en: "Once a strip of budget motels nicknamed \"Motel Row\" in the mid-1900s, this barrier-island city was rebuilt starting in the 1990s–2000s into a corridor of luxury oceanfront condo towers, drawing enough international buyers — especially from Russia and Latin America — to earn the nickname \"Little Moscow.\"",
      es: "Antes una franja de moteles económicos apodada \"Motel Row\" a mediados del siglo XX, esta ciudad en la isla barrera fue reconstruida a partir de los años 1990-2000 en un corredor de torres de condominios de lujo frente al mar, atrayendo suficientes compradores internacionales — especialmente de Rusia y América Latina — para ganarse el apodo de \"Little Moscow\".",
      fr: "Autrefois une bande de motels bon marché surnommée « Motel Row » au milieu du XXe siècle, cette ville d'île-barrière a été reconstruite à partir des années 1990-2000 en un corridor de tours de condos de luxe en front de mer, attirant suffisamment d'acheteurs internationaux — notamment de Russie et d'Amérique latine — pour gagner le surnom de « Little Moscow ».",
      ht: "Yon fwa se te yon bann motèl bon mache yo te bay ti non \"Motel Row\" nan mitan ane 1900 yo, vil sa a ki sou yon zile bawyè te rekonstwi kòmanse nan ane 1990-2000 yo pou vin yon koridò tou kondo liks bò lanmè, li te atire ase achtè entènasyonal — espesyalman soti Larisi ak Amerik Latin — pou l resevwa ti non \"Little Moscow.\"",
      pt: "Antes uma faixa de motéis econômicos apelidada de \"Motel Row\" em meados do século XX, essa cidade em uma ilha-barreira foi reconstruída a partir dos anos 1990-2000 em um corredor de torres de condomínios de luxo à beira-mar, atraindo compradores internacionais suficientes — especialmente da Rússia e da América Latina — para ganhar o apelido de \"Little Moscow\".",
      it: "Un tempo una fila di motel economici soprannominata \"Motel Row\" a metà del Novecento, questa città su un'isola barriera fu ricostruita a partire dagli anni '90-2000 in un corridoio di torri di condomini di lusso sul mare, attirando abbastanza acquirenti internazionali — soprattutto da Russia e America Latina — da guadagnarsi il soprannome di \"Little Moscow\".",
    },
    pricing: {
      singleFamily: { value: null, note: { en: "Almost no single-family homes — this is a barrier-island condo market.", es: "Casi no hay casas unifamiliares — este es un mercado de condominios en isla barrera." } },
      condo: { value: 749000, note: { en: "Luxury oceanfront towers push the median well above nearby areas; some units trade above $1.3M.", es: "Las torres de lujo frente al mar elevan la mediana muy por encima de las áreas cercanas; algunas unidades se venden por encima de $1.3M." } },
    },
  },
  {
    slug: "aventura",
    name: "Aventura",
    image: "/images/aventura.jpg",
    tagline: {
      en: "Shopping, high-rises, planned community",
      es: "Compras, rascacielos, comunidad planificada",
      fr: "Shopping, gratte-ciels, communauté planifiée",
      ht: "Achte, gratsyèl, kominote planifye",
      pt: "Compras, prédios altos, comunidade planejada",
      it: "Shopping, grattacieli, comunità pianificata",
    },
    history: {
      en: "Developed starting in the 1970s by Don Soffer as a master-planned community anchored by Aventura Mall, one of the largest shopping centers in the US, Aventura grew into a dense corridor of luxury condo towers and became its own incorporated city in 1995.",
      es: "Desarrollada a partir de la década de 1970 por Don Soffer como una comunidad planificada anclada en Aventura Mall, uno de los centros comerciales más grandes de EE. UU., Aventura creció hasta convertirse en un denso corredor de torres de condominios de lujo y se convirtió en su propia ciudad incorporada en 1995.",
      fr: "Développée à partir des années 1970 par Don Soffer comme une communauté planifiée ancrée par l'Aventura Mall, l'un des plus grands centres commerciaux des États-Unis, Aventura est devenue un corridor dense de tours de condos de luxe et une ville constituée à part entière en 1995.",
      ht: "Devlope kòmanse nan ane 1970 yo pa Don Soffer kòm yon kominote byen planifye ki ankre pa Aventura Mall, youn nan pi gwo sant komèsyal nan Etazini, Aventura te grandi vin yon koridò dans ak tou kondo liks epi li te vin pwòp vil enkòpore li an 1995.",
      pt: "Desenvolvida a partir da década de 1970 por Don Soffer como uma comunidade planejada ancorada pelo Aventura Mall, um dos maiores centros comerciais dos EUA, Aventura cresceu até se tornar um corredor denso de torres de condomínios de luxo e se tornou sua própria cidade incorporada em 1995.",
      it: "Sviluppata a partire dagli anni '70 da Don Soffer come comunità pianificata incentrata sull'Aventura Mall, uno dei più grandi centri commerciali degli Stati Uniti, Aventura è cresciuta fino a diventare un denso corridoio di torri di condomini di lusso ed è diventata una città a sé stante nel 1995.",
    },
    pricing: {
      singleFamily: { value: 480000, note: { en: "A small slice of the market — Aventura is overwhelmingly condo towers.", es: "Una pequeña parte del mercado — Aventura es abrumadoramente de torres de condominios." } },
      condo: { value: 550000, note: { en: "Wide range from older towers to new luxury high-rises near the mall.", es: "Amplio rango desde torres antiguas hasta nuevos rascacielos de lujo cerca del centro comercial." } },
    },
  },
  {
    slug: "hallandale-beach",
    name: "Hallandale Beach",
    image: "/images/hallandale-beach.jpg",
    tagline: {
      en: "Beachfront, condos, quiet",
      es: "Frente a la playa, condominios, tranquilo",
      fr: "Front de mer, condos, tranquille",
      ht: "Bò plaj, kondo, trankil",
      pt: "Litoral, condomínios, tranquilo",
      it: "Fronte spiaggia, condomini, tranquillo",
    },
    history: {
      en: "A historically working-class beach town in southern Broward County, Hallandale Beach transformed over the 2000s as Gulfstream Park's casino and beachfront condo development brought in new investment, while still remaining more affordable than its neighbors to the south.",
      es: "Un pueblo costero históricamente de clase trabajadora en el sur del condado de Broward, Hallandale Beach se transformó durante la década de 2000 cuando el casino de Gulfstream Park y el desarrollo de condominios frente a la playa atrajeron nuevas inversiones, aunque sigue siendo más asequible que sus vecinos al sur.",
      fr: "Historiquement une ville balnéaire de classe ouvrière dans le sud du comté de Broward, Hallandale Beach s'est transformée au cours des années 2000 lorsque le casino de Gulfstream Park et le développement de condos en front de mer ont apporté de nouveaux investissements, tout en restant plus abordable que ses voisines au sud.",
      ht: "Yon vil bò plaj ki istorikman se te klas travayè nan sid Konte Broward, Hallandale Beach te transfòme pandan ane 2000 yo lè kazino Gulfstream Park la ak devlopman kondo bò plaj la te pote nouvo envestisman, pandan li rete pi abòdab pase vwazen li yo nan sid la.",
      pt: "Historicamente uma cidade praiana de classe trabalhadora no sul do Condado de Broward, Hallandale Beach se transformou ao longo dos anos 2000, quando o cassino do Gulfstream Park e o desenvolvimento de condomínios à beira-mar trouxeram novos investimentos, embora continue mais acessível que suas vizinhas ao sul.",
      it: "Storicamente una città balneare di classe operaia nella parte meridionale della Contea di Broward, Hallandale Beach si è trasformata nel corso degli anni 2000, quando il casinò di Gulfstream Park e lo sviluppo di condomini sul mare hanno portato nuovi investimenti, pur restando più accessibile rispetto alle vicine a sud.",
    },
    pricing: {
      singleFamily: { value: 383000, note: { en: "Notably more affordable than Sunny Isles Beach or Aventura just to the south.", es: "Notablemente más asequible que Sunny Isles Beach o Aventura, justo al sur." } },
      condo: { value: 300000, note: { en: "A mix of older beachfront buildings and newer towers near Gulfstream Park.", es: "Una mezcla de edificios más antiguos frente a la playa y torres más nuevas cerca de Gulfstream Park." } },
    },
  },
  {
    slug: "kendall-pinecrest",
    name: "Kendall / Pinecrest",
    image: "/images/kendall-pinecrest.jpg",
    tagline: {
      en: "Suburban, tree-lined, top schools",
      es: "Suburbano, arbolado, mejores escuelas",
      fr: "Suburbain, arboré, écoles de premier plan",
      ht: "Sibèben, plen pyebwa, pi bon lekòl",
      pt: "Suburbano, arborizado, ótimas escolas",
      it: "Suburbano, alberato, scuole di alto livello",
    },
    history: {
      en: "Kendall, named for a 19th-century land manager for the Florida East Coast Railway, grew after WWII into a sprawling unincorporated suburb of shopping strips and family subdivisions. Pinecrest broke off to incorporate as its own village in 1996 specifically to preserve its oak-canopied streets and large lots, and is now home to some of Miami-Dade's top-rated public schools.",
      es: "Kendall, nombrado en honor a un administrador de tierras del siglo XIX del Florida East Coast Railway, creció después de la Segunda Guerra Mundial hasta convertirse en un extenso suburbio no incorporado de centros comerciales y urbanizaciones familiares. Pinecrest se separó para incorporarse como su propio pueblo en 1996 específicamente para preservar sus calles con dosel de robles y sus grandes lotes, y ahora alberga algunas de las escuelas públicas mejor calificadas de Miami-Dade.",
      fr: "Kendall, nommée d'après un gestionnaire foncier du XIXe siècle pour le Florida East Coast Railway, s'est développée après la Seconde Guerre mondiale en une vaste banlieue non constituée de centres commerciaux et de lotissements familiaux. Pinecrest s'en est détachée pour devenir son propre village en 1996, spécifiquement pour préserver ses rues bordées de chênes et ses grands terrains, et abrite aujourd'hui certaines des écoles publiques les mieux notées de Miami-Dade.",
      ht: "Kendall, yo te nonmen li dapre yon jesyonè tè nan 19yèm syèk la pou Florida East Coast Railway, li te grandi apre Dezyèm Gè Mondyal la pou vin yon gwo sibèb ki pa enkòpore ak strip komèsyal ak divizyon fanmi. Pinecrest te separe pou vin pwòp vilaj li an 1996 espesyalman pou prezève lari li yo ki gen gwo chenn (oak) k ap kouvri yo ak gwo teren, epi kounye a li se lakay kèk nan pi bon lekòl piblik Miami-Dade yo.",
      pt: "Kendall, batizada em homenagem a um administrador de terras do século XIX da Florida East Coast Railway, cresceu após a Segunda Guerra Mundial e se tornou um extenso subúrbio não incorporado de centros comerciais e loteamentos familiares. Pinecrest se separou para se tornar sua própria vila em 1996, especificamente para preservar suas ruas arborizadas com carvalhos e seus grandes lotes, e hoje abriga algumas das escolas públicas mais bem avaliadas de Miami-Dade.",
      it: "Kendall, il cui nome deriva da un amministratore fondiario ottocentesco della Florida East Coast Railway, crebbe dopo la Seconda Guerra Mondiale fino a diventare un vasto sobborgo non incorporato di centri commerciali e lottizzazioni familiari. Pinecrest se ne staccò per diventare un villaggio a sé nel 1996, specificamente per preservare le sue strade alberate di querce e i suoi ampi lotti, e oggi ospita alcune delle scuole pubbliche più quotate di Miami-Dade.",
    },
    pricing: {
      singleFamily: { value: 500000, note: { en: "Kendall runs closer to this citywide figure; incorporated Pinecrest next door is far pricier, often averaging $2.5M+.", es: "Kendall se acerca más a esta cifra general; el vecino Pinecrest, incorporado, es mucho más caro, con un promedio de $2.5M o más." } },
      condo: { value: 320000, note: { en: "Condo and townhome stock is concentrated in Kendall — Pinecrest has almost none and strongly favors single-family zoning.", es: "El inventario de condominios y casas adosadas se concentra en Kendall — Pinecrest tiene casi ninguno y favorece fuertemente la zonificación unifamiliar." } },
    },
  },
];

export function getAllNeighborhoods() {
  return neighborhoods;
}

export function getNeighborhood(slug) {
  return neighborhoods.find((n) => n.slug === slug);
}
